version: '3.8'

services:
  backend:
    stdin_open: true  
    tty: true 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - nswt_token=${nswt_token}
